# GPio
DHT_PIN = "GP21"
SOIL_SENSOR_PIN = "GP28" 
RELAY_PIN = "GP20" 
I2C_SCL_PIN = "GP17"
I2C_SDA_PIN = "GP16"

# Configuration Constants
MAX_ATTEMPTS = 100
HUMIDITY_AIR = 43450
HUMIDITY_WATER = 15011
MAX_READINGS = 210
READING_INTERVAL = 1800
NEED_HUMIDITY = 50
TIME_WATER = 5  
FINISH_BAN_TIME="09:00"
START_BAN_TIME="23:30"

# Code Constants
MAX_ATTEMPTS = 100
CHUNK_SIZE = 512
DAY = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

# Limit Constants
MIN_MAX_READINGS = 1
MAX_MAX_READINGS = 10000

MIN_READING_INTERVAL = 4  #await asyncio.sleep(4) when read sensors
MAX_READING_INTERVAL = 86400

MIN_NEED_HUMIDITY = 20
MAX_NEED_HUMIDITY = 80

MIN_TIME_WATER = 4
MAX_TIME_WATER = 15